### ISSUE TITLE
deliver md5sum in image response

### ISSUE THREAD

**Issue by aparcar** [aparcar/gsoc17-attended-sysupgrade#1]
The routers should verify the checksum before installation

**Comment by dangowrt** [comment]
... or even a signature? `usign` should be available on most systems...
See also [Bastian's talk on BattleMesh v10](https://schedule.battlemesh.org/system/event_attachments/attachments/000/000/001/original/slides.pdf)

**Comment by aparcar** [comment]
fixed a08f952c1dbd18689e92c5b84f1ed5049c99ffa0
