### ISSUE TITLE
Depend on luci-base instead of luci

### ISSUE THREAD

**Issue by p4u** [aparcar/gsoc17-attended-sysupgrade#10]
Current attended-sysupgrade package depends on "luci" which is a collection. Would it be possible to depend only on luci-base as libremesh is doing for webui package?

https://github.com/libremesh/lime-packages/blob/develop/packages/lime-webui/Makefile

This is IMO a requirement to better fit into 4MB routers.

**Comment by aparcar** [comment]
thanks for reporting
