### ISSUE TITLE
split existing opkg package and add package for upgrade-server

### ISSUE THREAD

**Issue by dangowrt** [aparcar/gsoc17-attended-sysupgrade#11]
The attended-sysupgrade package should be split into
* rpcd-mod-imageinfo
* luci-app-attendedsysupgrade

The upgrade-server should also be provided as an OpenWrt package. Ideally, the parameters of the update-server should be read from UCI and an init script should be created.

**Comment by dangowrt** [comment]
https://github.com/aparcar/gsoc17-attended-sysupgrade/pull/13

**Comment by aparcar** [comment]
partly done, rpcd-mod-imageinfo is a big feature which will be added later
right now we have
* rpcd-mod-attended-sysupgrade
* rpcd-mod-packagelist
* luci-app-attended-syupsgrade

see edaf7baac517eeb4407d344ddccc1bfcf00c6bc6 for details
