### ISSUE TITLE
make workdir configurable

### ISSUE THREAD

**Issue by dangowrt** [aparcar/gsoc17-attended-sysupgrade#17]
make work directory of the image server configurable
currently, `tempdir` is used for the downloads, however, `$PWD/imagebuilder` is still being used to extract the downloaded file.

**Comment by dangowrt** [comment]
Related to https://github.com/aparcar/gsoc17-attended-sysupgrade/issues/18

**Comment by aparcar** [comment]
fixed in 68cab3454c676894ac3c0f9344d190089ecac7e8
