### ISSUE TITLE
tmpdir or tempdir?

### ISSUE THREAD

**Issue by dangowrt** [aparcar/gsoc17-attended-sysupgrade#18]
https://github.com/aparcar/gsoc17-attended-sysupgrade/commit/8f60c7979acb2cc8f7564e426b50e0380bd2add4 introduced a config variable 'tempdir' but later on sets 'tmpdir'. Also https://github.com/aparcar/gsoc17-attended-sysupgrade/commit/7cb84bd03cc7251de4e083d3664b9fa2de5b25f2 didn't fix that.

in config.yml.default
```
tmpdir: None
```

in imagebuilder.py
```
with tempfile.TemporaryDirectory(dir=self.config.get("tempdir")) as tar_folder:
```

**Comment by aparcar** [comment]
fixed in 68cab3454c676894ac3c0f9344d190089ecac7e8
