### ISSUE TITLE
possibility of different updateserver 

### ISSUE THREAD

**Issue by FreifunkUFO** [aparcar/gsoc17-attended-sysupgrade#27]
before clicking the "search update" button the adress of the update-server should appear.

it also should be editable! (in order to use a different updateserver)

![att-wizawrd1](https://user-images.githubusercontent.com/2579265/29125676-ad72ad28-7d1c-11e7-8d32-95b26b719661.png)

**Comment by aparcar** [comment]
currently you can edit the option via uci in `/etc/config/attendedsysupgrade`. A config will be added to the web-view

**Comment by aparcar** [comment]
currently we have 2 active server:
* ledeupdate.planetexpress.cc
* betaupdate.libremesh.org

I move this issue to https://github.com/aparcar/gsoc17-attended-sysupgrade/issues/52

**Comment by FreifunkUFO** [comment]
i cant see any mention about this issue at referenced #52

**Comment by aparcar** [comment]
@FreifunkUFO checkout the initial post, it has a ToDo list attached
