### ISSUE TITLE
browserproblems with firefox 

### ISSUE THREAD

**Issue by FreifunkUFO** [aparcar/gsoc17-attended-sysupgrade#28]
with firefox i cant click the "search" button.
with cromium all is set. my OS is ubuntu

**Comment by aparcar** [comment]
please press str+shift+k in firefox to see the console output. does it show any error messages?

**Comment by aparcar** [comment]
@FreifunkUFO ping

**Comment by FreifunkUFO** [comment]
yes, it does. the error is called "Fehler". 
(btw. Firefox is available at http://mozilla.org)

**Comment by aparcar** [comment]
I'm using Firefox while developing and did not acknowledge this behaviour yet. What version do you use?

**Comment by FreifunkUFO** [comment]
it might be the most current version. i was also trying with outdated version.
btw: i was trying LEDE with freifunk-settings, built with meshkit via imagebuilder

**Comment by aparcar** [comment]
I tried the following versions of Firefox and all worked without a problem:
* 52.2.0 (64-bit)
* 55.0 (64-bit)
* 57.0a1 (2017-08-15) (64-bit)
All work as expected.

The MeshKit image x86/64 would boot, stuck on the following message forever:
`Waiting for root device /dev/mtdblock0...`

Is there a more verbose output than just "Fehler" possible?

**Comment by aparcar** [comment]
@FreifunkUFO did we resolv this issue via IRC?

**Comment by aparcar** [comment]
closing due to no response
worked here with all current Firefox releases (on linux)
