### ISSUE TITLE
make the packages-list editable 

### ISSUE THREAD

**Issue by FreifunkUFO** [aparcar/gsoc17-attended-sysupgrade#30]
when requesting the image there should be a possibility to VIEW AND CHANGE the list of packages

**Comment by FreifunkUFO** [comment]
![att-wizawrd2](https://user-images.githubusercontent.com/2579265/29127201-b88a8876-7d20-11e7-9dfe-d5409ab71215.png)

**Comment by aparcar** [comment]
Viewing is already planed, changing is something, if even planed, for after the GSoC

**Comment by aparcar** [comment]
currently a simple implementation would be to disable single packages via checkboxes. 
adding packages is more complicated as there won't be a auto completion for package names. 
@FreifunkUFO would the first version help you?

**Comment by aparcar** [comment]
this is a request for luci-app-attendedupgrade. I will shortly create a PR for that on openwrt/luci

**Comment by FreifunkUFO** [comment]
so please keep this ticket open!?

**Comment by aparcar** [comment]
https://github.com/openwrt/luci/pull/1404

**Comment by FreifunkUFO** [comment]
nice!

the layout is getting even more worse with every change/wish :-)

![freifunk-sysup-att](https://user-images.githubusercontent.com/2579265/31826797-4c971390-b5b6-11e7-8edd-a047a60d3d10.png)

**Comment by aparcar** [comment]
It looks a bit better on the official bootstrap version, but feel free to add design suggestions :)
