### ISSUE TITLE
use existing methods to upload/flash firmware

### ISSUE THREAD

**Issue by FreifunkUFO** [aparcar/gsoc17-attended-sysupgrade#32]
within luci1 and even luci2 there are possibilities to upload/flash the firmware.
so there might be no need to program a new way, and no need to need the cgi-io package

**Comment by aparcar** [comment]
If I'm not mistaken, `luci-ng` uses [luci2-io-helper](https://github.com/jow-/luci-ng/tree/master/luci2-io-helper) which was [merged](https://github.com/openwrt/packages/commit/e7b5bdd9e90443bcb78f8d7f90e01a2b8d215991) into `cgi-io`. So actually my approach uses already the `luci-ng` dependencies. 

Using `cgi-io` returns a checksum which can be auto compared with the checksum delivered by the server. Using Luci1 flash view does not offer this
