### ISSUE TITLE
uhttpd-mod-ubus is needed

### ISSUE THREAD

**Issue by FreifunkUFO** [aparcar/gsoc17-attended-sysupgrade#33]
trying freifunk-meshkit with luci via imagebuilder makes me need to install uhttpd-mod-ubus manually to get the attended-sysupgrade running.

there was no error message (ob webui) about that (or about problems)

**Comment by FreifunkUFO** [comment]
pull request is at https://github.com/openwrt/luci/pull/1290

you also could fix it in dependencies of rpcd-mod-attendedsysupgrade!?

**Comment by aparcar** [comment]
@FreifunkUFO `rpcd-mod-attendedsysupgrade` is useable by a CLI as well without the need of a `/ubus` call via http

**Comment by aparcar** [comment]
https://github.com/openwrt/luci/pull/1290

**Comment by aparcar** [comment]
merged in upstream
