### ISSUE TITLE
checkbox to flash firmware WITHOUT keeping settings

### ISSUE THREAD

**Issue by FreifunkUFO** [aparcar/gsoc17-attended-sysupgrade#34]
especially with auto-config firmwares (gluon, libremesh,..) there is no need to keep settings (all files in /etc/config/ )
so the attended-sysupgrade should have a checkbox for "keep no settings / delete all settings"

on standard firmware-upgrade webui-page there is such a checkbox for years

**Comment by aparcar** [comment]
I'll reuse the official code of Luci1

**Comment by aparcar** [comment]
waiting for https://github.com/openwrt/luci/pull/1295

**Comment by aparcar** [comment]
Just merged

**Comment by aparcar** [comment]
Just merged
