### ISSUE TITLE
button doenst work atm: Search for update -> Access denied

### ISSUE THREAD

**Issue by FreifunkUFO** [aparcar/gsoc17-attended-sysupgrade#38]
today i was trying last lede-release on x86, and was installing official lede trunk packages for attended sysupgrade.

atm all ubus-http-request (without pressing any button) got "Access denied"

**Comment by FreifunkUFO** [comment]
![freifunk-attsysu-1](https://user-images.githubusercontent.com/2579265/29382881-60ec33ea-82ce-11e7-9451-f54de96ac4b4.png)

**Comment by FreifunkUFO** [comment]
only happening with lede-release! (some luci stuff was changed)

but using this tool here to upgrade lede-release to lede-trunk is still very important. i think we have to opkg-update that luci-package too, when installing luci-attended-sysupgrade from snapshop to avoid this problem.

how is the name of that luci-package?

**Comment by aparcar** [comment]
@jow- the special luci1 was recently merged into luci snapshots and removed from my script. Do you see a way to make luci-app-attendedsyupgrade run on older releases?

**Comment by aparcar** [comment]
fixed with https://github.com/openwrt/luci/pull/1314

**Comment by FreifunkUFO** [comment]
how is the name of that luci-package?

**Comment by aparcar** [comment]
luci-app-attendedsysupgrade

**Comment by FreifunkUFO** [comment]
LOL no.

there were some further changes in luci needed. so my question is about the package according to former question:

> Do you see a way to make luci-app-attendedsyupgrade run on older releases?

**Comment by aparcar** [comment]
I recently created some pull requests asking to add the project to lede-17.01 stable branch. I'll keep you updated

Am 21. Oktober 2017 21:48:37 MESZ schrieb FreifunkUFO <notifications@github.com>:
