### ISSUE TITLE
bug: packagelist will not be sent atm

### ISSUE THREAD

**Issue by FreifunkUFO** [aparcar/gsoc17-attended-sysupgrade#39]
trying the todays trunk makes me wonder.
sysupgrade was working, but there was no routingprotocol or luci anymore

**Comment by FreifunkUFO** [comment]
![freifunk-attsy-2](https://user-images.githubusercontent.com/2579265/29388542-9097fe96-82e5-11e7-8248-cc64866aaf40.png)

**Comment by aparcar** [comment]
this is an error only happening updating a snapshot to a snapshot with exactly the same versions of packages. However, this is fixed in PR https://github.com/openwrt/luci/pull/1306
