### ISSUE TITLE
target currently not supported x86/generic

### ISSUE THREAD

**Issue by FreifunkUFO** [aparcar/gsoc17-attended-sysupgrade#46]
Rumors came up that there were changes on the project to allow to de-activate opkg-packages while upgrading via attended-sysgrade. i couldnt find something like that. (this morning i was upgrading a vm several times.)

this afternoon im not able to upgrade that same vm anymore:

target currently not supported x86/generic

**Comment by aparcar** [comment]
Due to a database reset all devices seemed "unsupported", fixed by now.
