### ISSUE TITLE
implement package list transformations

### ISSUE THREAD

**Issue by dangowrt** [aparcar/gsoc17-attended-sysupgrade#5]
packages are sometimes removed (`kmod-ipv6`), renamed (`libpolarssl` -> `libmbedtls`) or split into several build variants (`openvpn` -> `openvpn-openssl`, `openvpn-mbedtls`, ...).
Hence when generating the list of packages to be included in an updated image, those changes need to be taken into account.
Implement this by having a set of rules specifying the replacement operations in a context-aware fashion (ie. use `openvpn-mbedtls` if `libmbedtls` is already going to be installed)

**Comment by aparcar** [comment]
this issue is solved for now. In a later version it would be nice to point out what packages changed but that's future
