### ISSUE TITLE
Remove hash in image when using standard packages

### ISSUE THREAD

**Issue by aparcar** [aparcar/gsoc17-attended-sysupgrade#50]
This should result in the same build tree as for the official buildbot

**Comment by dangowrt** [comment]
> This should result in the same build tree as for the official buildbot

True for snapshot builds, not true for releases which (for now) come
with LuCI pre-installed.

**Comment by aparcar** [comment]
What do you think of batch creating all standard 17.01.3 images with luci installed and leave away the hash?

**Comment by aparcar** [comment]
@dangowrt would you suggest to add luci to lede build if no other package is specified?
