### ISSUE TITLE
build problems: Profile does not exist!

### ISSUE THREAD

**Issue by FreifunkUFO** [aparcar/gsoc17-attended-sysupgrade#55]
atm sysupgrade wont work for me:

[
    "lede",
    "snapshot",
    "ar71xx",
    "generic",
    "tl-wr902ac-v1",
    "f5b148faad84",
    ""
]

Profile "tl-wr902ac-v1" does not exist!
Use "make info" to get a list of available profile names.
Makefile:197: recipe for target 'image' failed
make: *** [image] Error 1

**Comment by FreifunkUFO** [comment]
also jefe.tk is affected:
when building image:
internal server error. please try again later

**Comment by aparcar** [comment]
Is it possible that the daily snapshot does not support the device?

**Comment by FreifunkUFO** [comment]
the device was supported by LEDE the last weeks and running nice.
but you are true: @hauke killed the device recently :-(

https://github.com/lede-project/source/commit/f7a6fd31539be54d14d7c52b491b40b26bf8f740

**Comment by aparcar** [comment]
using snapshots means living on the edge - sorry can't do anything about it currently
